//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShopManagement
{
    /// <summary>
    /// Defines the <see cref="login" />.
    /// </summary>
    public partial class login
    {
        /// <summary>
        /// form1 control..
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// TextBox1 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox1;

        /// <summary>
        /// TextBox2 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox2;

        /// <summary>
        /// Button1 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button1;
    }
}
